name: ino_dev CI 🌵

on:
  push:
    branches:
      - ino_dev
  pull_request:
    branches:
      - ino_dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: List repo contents
        run: ls -la

      - name: List sqlite_devops contents
        run: ls -la sqlite_devops

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Dockerfile.builder
        run: |
          docker build -t sqlite_builder -f sqlite_devops/Dockerfile.builder sqlite_devops

      - name: Archive build artifact
        if: success()
        run: |
          mkdir -p artifacts
          echo "Fake binary or export content" > artifacts/dummy_binary.txt

      - name: 📤 Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/
